import type {
  AuditEntry,
  CanonicalEntity,
  Case,
  CrossCaseLink,
  Evidence,
  Finding,
  GraphEdge,
  RawMention,
  ResolutionCandidate,
  TimelineEvent,
  User,
} from './types'

// -------------------------------------------------------------------------------------
// DEMO USERS (prototype only — passwords are plaintext seed values, never real practice)
// -------------------------------------------------------------------------------------
export const users: User[] = [
  {
    id: 'u-mira',
    name: 'Insp. Mira Rao',
    email: 'mira.rao@nexus.gov',
    username: 'mira',
    password: 'demo1234',
    role: 'senior_investigator',
    agency: 'State Crime Branch',
    clearance: 'SECRET',
    caseAccess: 'ALL',
  },
  {
    id: 'u-arjun',
    name: 'SI. Arjun Nair',
    email: 'arjun.nair@nexus.gov',
    username: 'arjun',
    password: 'demo1234',
    role: 'investigator',
    agency: 'State Crime Branch',
    clearance: 'CONFIDENTIAL',
    caseAccess: ['case-101'],
  },
  {
    id: 'u-lena',
    name: 'Lena Fernandes',
    email: 'lena.fernandes@nexus.gov',
    username: 'lena',
    password: 'demo1234',
    role: 'analyst',
    agency: 'Financial Intelligence Unit',
    clearance: 'CONFIDENTIAL',
    caseAccess: ['case-101', 'case-205'],
  },
  {
    id: 'u-dev',
    name: 'DySP. Dev Menon',
    email: 'dev.menon@nexus.gov',
    username: 'dev',
    password: 'demo1234',
    role: 'supervisor',
    agency: 'State Crime Branch',
    clearance: 'SECRET',
    caseAccess: 'ALL',
  },
  {
    id: 'u-admin',
    name: 'System Administrator',
    email: 'admin@nexus.gov',
    username: 'admin',
    password: 'demo1234',
    role: 'admin',
    agency: 'NEXUS-CI Operations',
    clearance: 'SECRET',
    caseAccess: 'ALL',
  },
]

// -------------------------------------------------------------------------------------
// CASES
// -------------------------------------------------------------------------------------
export const cases: Case[] = [
  {
    id: 'case-101',
    title: 'Operation Meridian — Layered Fund Movement',
    description:
      'Investigation into a suspected fund-layering operation linked to a series of coordinated calls and staged account transfers around Central Station.',
    status: 'active',
    priority: 'high',
    createdAt: '2026-08-02T09:12:00Z',
    updatedAt: '2026-08-27T16:40:00Z',
    assignedTo: 'u-mira',
    agency: 'State Crime Branch',
    classification: 'CONFIDENTIAL',
  },
  {
    id: 'case-205',
    title: 'Harbor Warehouse — Cross-Border Transfers',
    description:
      'Parallel financial investigation involving a warehouse logistics front. Early analysis suggests overlap with Operation Meridian entities.',
    status: 'under_review',
    priority: 'critical',
    createdAt: '2026-08-14T11:05:00Z',
    updatedAt: '2026-08-28T08:20:00Z',
    assignedTo: 'u-dev',
    agency: 'Financial Intelligence Unit',
    classification: 'SECRET',
  },
  {
    id: 'case-317',
    title: 'Transit Corridor — Vehicle Movement Review',
    description:
      'Vehicle sighting review along the northern transit corridor. Currently in intake; limited evidence ingested.',
    status: 'cold',
    priority: 'low',
    createdAt: '2026-07-20T14:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
    assignedTo: 'u-arjun',
    agency: 'State Crime Branch',
    classification: 'RESTRICTED',
  },
]

// -------------------------------------------------------------------------------------
// CANONICAL ENTITIES (with deterministic graph layout positions, viewBox 1040 x 640)
// -------------------------------------------------------------------------------------
export const entities: CanonicalEntity[] = [
  {
    id: 'p-ravi',
    type: 'person',
    label: 'Ravi Kumar',
    subtitle: 'Person of interest',
    caseIds: ['case-101', 'case-205'],
    aliases: ['Ravi Kumar', 'R. Kumar', 'Ravi K.'],
    relevance: 87,
    attributes: { 'National ID': 'XXXX-2291', Age: '41', Role: 'Recurring across cases' },
    x: 520,
    y: 330,
    cluster: 'A',
  },
  {
    id: 'p-arun',
    type: 'person',
    label: 'Arun Prasad',
    subtitle: 'Associate',
    caseIds: ['case-101'],
    aliases: ['Arun', 'A. Prasad'],
    relevance: 64,
    attributes: { Age: '38', Role: 'Frequent contact' },
    x: 300,
    y: 240,
    cluster: 'A',
  },
  {
    id: 'p-suresh',
    type: 'person',
    label: 'Suresh Iyer',
    subtitle: 'Associate',
    caseIds: ['case-101'],
    aliases: ['Suresh'],
    relevance: 41,
    attributes: { Age: '52' },
    x: 250,
    y: 440,
    cluster: 'A',
  },
  {
    id: 'p-vijay',
    type: 'person',
    label: 'Vijay Menon',
    subtitle: 'Person of interest',
    caseIds: ['case-205'],
    aliases: ['Vijay', 'V. Menon'],
    relevance: 58,
    attributes: { Age: '45', Role: 'Warehouse contact' },
    x: 790,
    y: 330,
    cluster: 'C',
  },
  {
    id: 'p-rkumar',
    type: 'person',
    label: 'R. Kumar',
    subtitle: 'Candidate duplicate of Ravi Kumar',
    caseIds: ['case-205'],
    aliases: ['R. Kumar'],
    relevance: 52,
    attributes: { Note: 'Pending human review' },
    x: 660,
    y: 470,
    cluster: 'C',
  },
  {
    id: 'tel-1',
    type: 'phone',
    label: '+91 98765 43210',
    subtitle: "Ravi Kumar's primary line",
    caseIds: ['case-101', 'case-205'],
    aliases: ['9876543210'],
    relevance: 79,
    attributes: { Carrier: 'BharatCell', 'First seen': '01 Aug 2026' },
    x: 430,
    y: 235,
    cluster: 'A',
  },
  {
    id: 'tel-2',
    type: 'phone',
    label: '+91 98123 45678',
    subtitle: "Arun Prasad's line",
    caseIds: ['case-101'],
    aliases: ['9812345678'],
    relevance: 55,
    attributes: { Carrier: 'BharatCell' },
    x: 250,
    y: 165,
    cluster: 'A',
  },
  {
    id: 'tel-3',
    type: 'phone',
    label: '+91 99000 11122',
    subtitle: "Vijay Menon's line",
    caseIds: ['case-205'],
    aliases: ['9900011122'],
    relevance: 44,
    attributes: { Carrier: 'MetroTel' },
    x: 900,
    y: 270,
    cluster: 'C',
  },
  {
    id: 'veh-1',
    type: 'vehicle',
    label: 'TN01 AB 1234',
    subtitle: 'Registered to Ravi Kumar',
    caseIds: ['case-101'],
    aliases: ['TN01AB1234'],
    relevance: 49,
    attributes: { Make: 'Sedan', Color: 'Silver' },
    x: 190,
    y: 540,
    cluster: 'A',
  },
  {
    id: 'acc-101',
    type: 'account',
    label: 'Account A101',
    subtitle: 'Held by Ravi Kumar',
    caseIds: ['case-101'],
    aliases: ['A101'],
    relevance: 61,
    attributes: { Bank: 'Union Commercial', Type: 'Savings' },
    x: 400,
    y: 460,
    cluster: 'A',
  },
  {
    id: 'acc-205',
    type: 'account',
    label: 'Account A205',
    subtitle: 'Intermediary account',
    caseIds: ['case-101', 'case-205'],
    aliases: ['A205'],
    relevance: 66,
    attributes: { Bank: 'Coastal Bank', Type: 'Current' },
    x: 560,
    y: 500,
    cluster: 'A',
  },
  {
    id: 'acc-b',
    type: 'account',
    label: 'Account B',
    subtitle: 'Held by Arun Prasad',
    caseIds: ['case-205'],
    aliases: ['Account B'],
    relevance: 63,
    attributes: { Bank: 'Coastal Bank', Type: 'Current' },
    x: 710,
    y: 540,
    cluster: 'C',
  },
  {
    id: 'acc-x',
    type: 'account',
    label: 'Account X',
    subtitle: 'Terminal account of interest',
    caseIds: ['case-205'],
    aliases: ['Account X'],
    relevance: 71,
    attributes: { Bank: 'Offshore Nominee', Type: 'Nominee' },
    x: 880,
    y: 480,
    cluster: 'C',
  },
  {
    id: 'loc-central',
    type: 'location',
    label: 'Central Station',
    subtitle: 'Recurring meeting point',
    caseIds: ['case-101'],
    aliases: ['Central Station'],
    relevance: 47,
    attributes: { Type: 'Public transit hub' },
    x: 155,
    y: 320,
    cluster: 'A',
  },
  {
    id: 'loc-harbor',
    type: 'location',
    label: 'Harbor Warehouse 7',
    subtitle: 'Logistics front',
    caseIds: ['case-205'],
    aliases: ['Harbor Warehouse'],
    relevance: 45,
    attributes: { Type: 'Warehouse' },
    x: 900,
    y: 400,
    cluster: 'C',
  },
  {
    id: 'org-meridian',
    type: 'org',
    label: 'Meridian Traders',
    subtitle: 'Suspected shell entity',
    caseIds: ['case-101', 'case-205'],
    aliases: ['Meridian Traders Pvt Ltd'],
    relevance: 68,
    attributes: { Registered: '2024', Directors: '2' },
    x: 640,
    y: 210,
    cluster: 'A',
  },
]

// -------------------------------------------------------------------------------------
// GRAPH EDGES (each carries evidence, confidence, timeframe, rationale)
// -------------------------------------------------------------------------------------
export const edges: GraphEdge[] = [
  {
    id: 'e-ravi-tel1',
    source: 'p-ravi',
    target: 'tel-1',
    type: 'OWNS',
    confidence: 96,
    occurrences: 1,
    timeframe: { from: '2026-08-01', to: '2026-08-12' },
    evidenceIds: ['ev-fir-101', 'ev-cdr-101'],
    createdByPipeline: 'entity-resolution',
    rationale: 'Subscriber records and the FIR both attribute this line to Ravi Kumar.',
  },
  {
    id: 'e-ravi-veh1',
    source: 'p-ravi',
    target: 'veh-1',
    type: 'OWNS',
    confidence: 92,
    occurrences: 1,
    timeframe: { from: '2026-08-02', to: '2026-08-02' },
    evidenceIds: ['ev-veh-101'],
    createdByPipeline: 'ingestion',
    rationale: 'Vehicle registry lists Ravi Kumar as the registered owner.',
  },
  {
    id: 'e-ravi-acc101',
    source: 'p-ravi',
    target: 'acc-101',
    type: 'OWNS',
    confidence: 90,
    occurrences: 1,
    timeframe: { from: '2026-08-03', to: '2026-08-03' },
    evidenceIds: ['ev-txn-101'],
    createdByPipeline: 'ingestion',
    rationale: 'Account A101 KYC record matches Ravi Kumar.',
  },
  {
    id: 'e-tel1-tel2',
    source: 'tel-1',
    target: 'tel-2',
    type: 'CALLS',
    confidence: 94,
    occurrences: 14,
    timeframe: { from: '2026-08-01', to: '2026-08-12' },
    evidenceIds: ['ev-cdr-101'],
    createdByPipeline: 'cdr-parser',
    suspicious: true,
    rationale: '14 calls recorded between the two linked phone identifiers over 11 days.',
  },
  {
    id: 'e-arun-tel2',
    source: 'p-arun',
    target: 'tel-2',
    type: 'OWNS',
    confidence: 89,
    occurrences: 1,
    timeframe: { from: '2026-08-01', to: '2026-08-01' },
    evidenceIds: ['ev-cdr-101'],
    createdByPipeline: 'entity-resolution',
    rationale: 'Subscriber record attributes this line to Arun Prasad.',
  },
  {
    id: 'e-ravi-arun',
    source: 'p-ravi',
    target: 'p-arun',
    type: 'ASSOCIATED_WITH',
    confidence: 82,
    occurrences: 14,
    timeframe: { from: '2026-08-01', to: '2026-08-12' },
    evidenceIds: ['ev-cdr-101', 'ev-fir-101'],
    createdByPipeline: 'relationship-extraction',
    rationale: 'Frequent call contact and co-mention in the FIR narrative.',
  },
  {
    id: 'e-acc101-acc205',
    source: 'acc-101',
    target: 'acc-205',
    type: 'TRANSFERS',
    confidence: 88,
    occurrences: 3,
    timeframe: { from: '2026-08-04', to: '2026-08-09' },
    evidenceIds: ['ev-txn-101'],
    createdByPipeline: 'transaction-parser',
    suspicious: true,
    rationale: 'Three transfers totalling a value just under the reporting threshold.',
  },
  {
    id: 'e-acc205-accb',
    source: 'acc-205',
    target: 'acc-b',
    type: 'TRANSFERS',
    confidence: 85,
    occurrences: 2,
    timeframe: { from: '2026-08-09', to: '2026-08-15' },
    evidenceIds: ['ev-txn-101', 'ev-txn-205'],
    createdByPipeline: 'transaction-parser',
    suspicious: true,
    rationale: 'Funds forwarded within 24 hours of receipt — consistent with layering.',
  },
  {
    id: 'e-accb-accx',
    source: 'acc-b',
    target: 'acc-x',
    type: 'TRANSFERS',
    confidence: 83,
    occurrences: 2,
    timeframe: { from: '2026-08-15', to: '2026-08-20' },
    evidenceIds: ['ev-txn-205'],
    createdByPipeline: 'transaction-parser',
    suspicious: true,
    rationale: 'Final hop into a nominee account with no declared business purpose.',
  },
  {
    id: 'e-arun-accb',
    source: 'p-arun',
    target: 'acc-b',
    type: 'OWNS',
    confidence: 80,
    occurrences: 1,
    timeframe: { from: '2026-08-08', to: '2026-08-08' },
    evidenceIds: ['ev-txn-205'],
    createdByPipeline: 'ingestion',
    rationale: 'Account B KYC record matches Arun Prasad.',
  },
  {
    id: 'e-vijay-accx',
    source: 'p-vijay',
    target: 'acc-x',
    type: 'ASSOCIATED_WITH',
    confidence: 74,
    occurrences: 1,
    timeframe: { from: '2026-08-16', to: '2026-08-16' },
    evidenceIds: ['ev-fir-205'],
    createdByPipeline: 'relationship-extraction',
    rationale: 'Vijay Menon named as signatory contact for Account X in case 205 filing.',
  },
  {
    id: 'e-vijay-tel3',
    source: 'p-vijay',
    target: 'tel-3',
    type: 'OWNS',
    confidence: 86,
    occurrences: 1,
    timeframe: { from: '2026-08-14', to: '2026-08-14' },
    evidenceIds: ['ev-cdr-205'],
    createdByPipeline: 'entity-resolution',
    rationale: 'Subscriber record attributes this line to Vijay Menon.',
  },
  {
    id: 'e-tel1-tel3',
    source: 'tel-1',
    target: 'tel-3',
    type: 'CALLS',
    confidence: 77,
    occurrences: 5,
    timeframe: { from: '2026-08-14', to: '2026-08-19' },
    evidenceIds: ['ev-cdr-205'],
    createdByPipeline: 'cdr-parser',
    suspicious: true,
    rationale: 'Five calls bridging the Meridian and Harbor phone clusters.',
  },
  {
    id: 'e-ravi-central',
    source: 'p-ravi',
    target: 'loc-central',
    type: 'SEEN_AT',
    confidence: 70,
    occurrences: 2,
    timeframe: { from: '2026-08-05', to: '2026-08-11' },
    evidenceIds: ['ev-fir-101'],
    createdByPipeline: 'relationship-extraction',
    rationale: 'Two sightings noted in the FIR narrative.',
  },
  {
    id: 'e-arun-central',
    source: 'p-arun',
    target: 'loc-central',
    type: 'SEEN_AT',
    confidence: 66,
    occurrences: 1,
    timeframe: { from: '2026-08-05', to: '2026-08-05' },
    evidenceIds: ['ev-fir-101'],
    createdByPipeline: 'relationship-extraction',
    rationale: 'Co-sighting with Ravi Kumar recorded in the FIR.',
  },
  {
    id: 'e-suresh-ravi',
    source: 'p-suresh',
    target: 'p-ravi',
    type: 'ASSOCIATED_WITH',
    confidence: 58,
    occurrences: 2,
    timeframe: { from: '2026-08-03', to: '2026-08-06' },
    evidenceIds: ['ev-fir-101'],
    createdByPipeline: 'relationship-extraction',
    rationale: 'Named alongside Ravi Kumar in the complaint narrative.',
  },
  {
    id: 'e-ravi-meridian',
    source: 'p-ravi',
    target: 'org-meridian',
    type: 'ASSOCIATED_WITH',
    confidence: 72,
    occurrences: 1,
    timeframe: { from: '2026-08-03', to: '2026-08-03' },
    evidenceIds: ['ev-txn-101'],
    createdByPipeline: 'relationship-extraction',
    rationale: 'Ravi Kumar listed as a contact for Meridian Traders.',
  },
  {
    id: 'e-vijay-meridian',
    source: 'p-vijay',
    target: 'org-meridian',
    type: 'ASSOCIATED_WITH',
    confidence: 63,
    occurrences: 1,
    timeframe: { from: '2026-08-16', to: '2026-08-16' },
    evidenceIds: ['ev-fir-205'],
    createdByPipeline: 'relationship-extraction',
    rationale: 'Meridian Traders referenced in the case 205 filing.',
  },
  {
    id: 'e-vijay-harbor',
    source: 'p-vijay',
    target: 'loc-harbor',
    type: 'VISITED',
    confidence: 69,
    occurrences: 3,
    timeframe: { from: '2026-08-15', to: '2026-08-22' },
    evidenceIds: ['ev-fir-205'],
    createdByPipeline: 'relationship-extraction',
    rationale: 'Three logged visits to Harbor Warehouse 7.',
  },
  {
    id: 'e-rkumar-tel1',
    source: 'p-rkumar',
    target: 'tel-1',
    type: 'OWNS',
    confidence: 84,
    occurrences: 1,
    timeframe: { from: '2026-08-14', to: '2026-08-14' },
    evidenceIds: ['ev-cdr-205'],
    createdByPipeline: 'entity-resolution',
    rationale: 'Case 205 references the same line as case 101 — supports a candidate merge.',
  },
]

// -------------------------------------------------------------------------------------
// EVIDENCE
// -------------------------------------------------------------------------------------
export const evidence: Evidence[] = [
  {
    id: 'ev-fir-101',
    caseId: 'case-101',
    title: 'FIR 101/2026',
    sourceType: 'FIR',
    fileName: 'FIR101.pdf',
    sha256: 'a3f1c9e27b0d4a5e8f1b6c2d9e4a7b3c8d5e1f2a9b6c4d7e0f3a1b8c5d2e9f60',
    uploadedAt: '2026-08-02T09:20:00Z',
    uploadedBy: 'u-mira',
    sizeBytes: 248320,
    status: 'processed',
    relevance: 88,
    extractedText:
      'First Information Report 101/2026. Complainant reports a coordinated series of financial transactions. Ravi Kumar was observed at Central Station on two occasions alongside Arun Prasad. A silver sedan bearing registration TN01 AB 1234 was noted at the scene. The complaint references repeated phone contact between the named individuals and an entity styled Meridian Traders.',
    entityMentions: ['p-ravi', 'p-arun', 'p-suresh', 'loc-central', 'veh-1', 'org-meridian'],
  },
  {
    id: 'ev-cdr-101',
    caseId: 'case-101',
    title: 'Call Detail Records — Line 43210',
    sourceType: 'CDR',
    fileName: 'CDR101.csv',
    sha256: 'b7e2d0a41f6c3b8e9d2a5c7f0b4e1d8a6c3f9b2e5d7a0c4f1b8e3d6a9c2f5b08',
    uploadedAt: '2026-08-03T10:05:00Z',
    uploadedBy: 'u-mira',
    sizeBytes: 51204,
    status: 'processed',
    relevance: 82,
    rows: [
      { timestamp: '2026-08-01 09:14', caller: '9876543210', callee: '9812345678', duration: '212s' },
      { timestamp: '2026-08-02 18:40', caller: '9876543210', callee: '9812345678', duration: '95s' },
      { timestamp: '2026-08-04 11:02', caller: '9812345678', callee: '9876543210', duration: '311s' },
      { timestamp: '2026-08-07 20:17', caller: '9876543210', callee: '9812345678', duration: '46s' },
      { timestamp: '2026-08-12 08:55', caller: '9876543210', callee: '9812345678', duration: '178s' },
    ],
    entityMentions: ['tel-1', 'tel-2', 'p-ravi', 'p-arun'],
  },
  {
    id: 'ev-txn-101',
    caseId: 'case-101',
    title: 'Transaction Ledger — A101',
    sourceType: 'TRANSACTIONS',
    fileName: 'Transactions101.csv',
    sha256: 'c1d5b9e30a7f2c6b8e4d1a9c5f2b7e0d3a6c9f4b1e8d5a2c7f0b3e6d9a4c1f72',
    uploadedAt: '2026-08-03T10:40:00Z',
    uploadedBy: 'u-lena',
    sizeBytes: 33112,
    status: 'processed',
    relevance: 90,
    rows: [
      { date: '2026-08-04', from: 'A101', to: 'A205', amount: '48,500', channel: 'IMPS' },
      { date: '2026-08-06', from: 'A101', to: 'A205', amount: '49,000', channel: 'IMPS' },
      { date: '2026-08-09', from: 'A101', to: 'A205', amount: '47,800', channel: 'NEFT' },
      { date: '2026-08-09', from: 'A205', to: 'Account B', amount: '92,000', channel: 'RTGS' },
    ],
    entityMentions: ['acc-101', 'acc-205', 'acc-b', 'p-ravi', 'org-meridian'],
  },
  {
    id: 'ev-veh-101',
    caseId: 'case-101',
    title: 'Vehicle Registry Extract',
    sourceType: 'VEHICLE',
    fileName: 'Vehicles101.csv',
    sha256: 'd9a4c1f72e0b5d8a3c6f9b2e5d1a8c4f7b0e3d6a9c2f5b8e1d4a7c0f3b6e9d25',
    uploadedAt: '2026-08-03T11:10:00Z',
    uploadedBy: 'u-arjun',
    sizeBytes: 8842,
    status: 'processed',
    relevance: 61,
    rows: [{ plate: 'TN01AB1234', owner: 'Ravi Kumar', make: 'Sedan', color: 'Silver' }],
    entityMentions: ['veh-1', 'p-ravi'],
  },
  {
    id: 'ev-fir-205',
    caseId: 'case-205',
    title: 'FIR 205/2026',
    sourceType: 'FIR',
    fileName: 'FIR205.pdf',
    sha256: 'e3d6a9c2f5b8e1d4a7c0f3b6e9d2a5c8f1b4e7d0a3c6f9b2e5d8a1c4f7b0e3d6',
    uploadedAt: '2026-08-14T11:15:00Z',
    uploadedBy: 'u-dev',
    sizeBytes: 262100,
    status: 'processed',
    relevance: 85,
    extractedText:
      'First Information Report 205/2026. Financial intelligence flags a nominee account styled Account X. Vijay Menon is named as a signatory contact and was recorded visiting Harbor Warehouse 7 on multiple occasions. The filing references Meridian Traders and a line ending 43210 previously associated with case 101.',
    entityMentions: ['p-vijay', 'acc-x', 'loc-harbor', 'org-meridian', 'tel-1', 'p-rkumar'],
  },
  {
    id: 'ev-cdr-205',
    caseId: 'case-205',
    title: 'Call Detail Records — Harbor Cluster',
    sourceType: 'CDR',
    fileName: 'CDR205.csv',
    sha256: 'f7b0e3d6a9c2f5b8e1d4a7c0f3b6e9d2a5c8f1b4e7d0a3c6f9b2e5d8a1c4f70b',
    uploadedAt: '2026-08-15T09:30:00Z',
    uploadedBy: 'u-lena',
    sizeBytes: 44098,
    status: 'processed',
    relevance: 76,
    rows: [
      { timestamp: '2026-08-14 15:22', caller: '9876543210', callee: '9900011122', duration: '140s' },
      { timestamp: '2026-08-16 12:01', caller: '9900011122', callee: '9876543210', duration: '267s' },
      { timestamp: '2026-08-19 19:44', caller: '9876543210', callee: '9900011122', duration: '58s' },
    ],
    entityMentions: ['tel-1', 'tel-3', 'p-vijay', 'p-rkumar'],
  },
  {
    id: 'ev-txn-205',
    caseId: 'case-205',
    title: 'Transaction Ledger — Account B / X',
    sourceType: 'TRANSACTIONS',
    fileName: 'Transactions205.csv',
    sha256: '0a3c6f9b2e5d8a1c4f7b0e3d6a9c2f5b8e1d4a7c0f3b6e9d2a5c8f1b4e7d0a36',
    uploadedAt: '2026-08-15T10:00:00Z',
    uploadedBy: 'u-lena',
    sizeBytes: 29774,
    status: 'processed',
    relevance: 89,
    rows: [
      { date: '2026-08-15', from: 'A205', to: 'Account B', amount: '90,500', channel: 'RTGS' },
      { date: '2026-08-17', from: 'Account B', to: 'Account X', amount: '88,000', channel: 'RTGS' },
      { date: '2026-08-20', from: 'Account B', to: 'Account X', amount: '86,500', channel: 'SWIFT' },
    ],
    entityMentions: ['acc-205', 'acc-b', 'acc-x', 'p-arun', 'p-vijay'],
  },
]

// -------------------------------------------------------------------------------------
// RAW MENTIONS (pre-resolution)
// -------------------------------------------------------------------------------------
export const rawMentions: RawMention[] = [
  { id: 'rm-1', caseId: 'case-101', evidenceId: 'ev-fir-101', surface: 'Ravi Kumar', type: 'person', resolvedTo: 'p-ravi' },
  { id: 'rm-2', caseId: 'case-101', evidenceId: 'ev-cdr-101', surface: 'Ravi K.', type: 'person', resolvedTo: 'p-ravi' },
  { id: 'rm-3', caseId: 'case-205', evidenceId: 'ev-fir-205', surface: 'R. Kumar', type: 'person', resolvedTo: 'p-rkumar' },
  { id: 'rm-4', caseId: 'case-101', evidenceId: 'ev-fir-101', surface: 'Arun', type: 'person', resolvedTo: 'p-arun' },
]

// -------------------------------------------------------------------------------------
// ENTITY RESOLUTION CANDIDATES (human-in-the-loop)
// -------------------------------------------------------------------------------------
export const resolutionCandidates: ResolutionCandidate[] = [
  {
    id: 'res-1',
    caseId: 'case-205',
    canonicalId: 'p-ravi',
    canonicalLabel: 'Ravi Kumar',
    type: 'person',
    mentions: ['Ravi Kumar', 'R. Kumar', 'Ravi K.'],
    confidence: 91,
    signals: [
      { label: 'Name similarity', matched: true },
      { label: 'Phone match (43210)', matched: true },
      { label: 'Vehicle association', matched: true },
      { label: 'Case overlap (101 ↔ 205)', matched: true },
      { label: 'Address match', matched: false },
    ],
    status: 'pending',
  },
]

// -------------------------------------------------------------------------------------
// FINDINGS
// -------------------------------------------------------------------------------------
export const findings: Finding[] = [
  {
    id: 'f-bridge',
    caseId: 'case-101',
    title: 'Potential bridge entity: Ravi Kumar',
    category: 'potential_bridge',
    severity: 'high',
    confidence: 88,
    why: 'Ravi Kumar connects the Meridian call cluster and the Harbor financial cluster that are otherwise separate.',
    entityIds: ['p-ravi'],
    evidenceIds: ['ev-cdr-101', 'ev-cdr-205', 'ev-txn-101'],
    status: 'open',
    createdAt: '2026-08-20T12:00:00Z',
  },
  {
    id: 'f-chain',
    caseId: 'case-101',
    title: 'Suspicious transaction chain A101 → A205 → B → X',
    category: 'suspicious_transaction_chain',
    severity: 'high',
    confidence: 84,
    why: 'Four sequential transfers move funds toward a nominee account, each hop staying just under the reporting threshold.',
    entityIds: ['acc-101', 'acc-205', 'acc-b', 'acc-x'],
    evidenceIds: ['ev-txn-101', 'ev-txn-205'],
    status: 'open',
    createdAt: '2026-08-21T09:30:00Z',
  },
  {
    id: 'f-recurrence',
    caseId: 'case-205',
    title: 'Recurring entity across cases 101 and 205',
    category: 'cross_case_recurrence',
    severity: 'medium',
    confidence: 92,
    why: 'The phone line ending 43210 and a closely matching name appear in both investigations.',
    entityIds: ['tel-1', 'p-ravi', 'p-rkumar'],
    evidenceIds: ['ev-cdr-101', 'ev-cdr-205', 'ev-fir-205'],
    status: 'open',
    createdAt: '2026-08-22T14:10:00Z',
  },
  {
    id: 'f-comms',
    caseId: 'case-101',
    title: 'Anomalous communication pattern on line 43210',
    category: 'anomalous_communication',
    severity: 'medium',
    confidence: 73,
    why: 'Call frequency on the line spikes immediately before each recorded transfer.',
    entityIds: ['tel-1', 'tel-2'],
    evidenceIds: ['ev-cdr-101'],
    status: 'open',
    createdAt: '2026-08-23T08:00:00Z',
  },
]

// -------------------------------------------------------------------------------------
// TIMELINE
// -------------------------------------------------------------------------------------
export const timelineEvents: TimelineEvent[] = [
  { id: 't-1', caseId: 'case-101', timestamp: '2026-08-01T09:14:00Z', type: 'call', title: 'Call: 43210 → 45678 (212s)', entityIds: ['tel-1', 'tel-2'], evidenceId: 'ev-cdr-101' },
  { id: 't-2', caseId: 'case-101', timestamp: '2026-08-02T09:12:00Z', type: 'case_mention', title: 'FIR 101/2026 filed', entityIds: ['p-ravi', 'p-arun'], evidenceId: 'ev-fir-101' },
  { id: 't-3', caseId: 'case-101', timestamp: '2026-08-04T11:00:00Z', type: 'transfer', title: 'Transfer A101 → A205 (48,500)', entityIds: ['acc-101', 'acc-205'], evidenceId: 'ev-txn-101' },
  { id: 't-4', caseId: 'case-101', timestamp: '2026-08-05T17:30:00Z', type: 'sighting', title: 'Ravi Kumar & Arun seen at Central Station', entityIds: ['p-ravi', 'p-arun', 'loc-central'], evidenceId: 'ev-fir-101' },
  { id: 't-5', caseId: 'case-101', timestamp: '2026-08-09T14:20:00Z', type: 'transfer', title: 'Transfer A205 → Account B (92,000)', entityIds: ['acc-205', 'acc-b'], evidenceId: 'ev-txn-101' },
  { id: 't-6', caseId: 'case-205', timestamp: '2026-08-14T15:22:00Z', type: 'call', title: 'Call: 43210 → 11122 (140s)', entityIds: ['tel-1', 'tel-3'], evidenceId: 'ev-cdr-205' },
  { id: 't-7', caseId: 'case-205', timestamp: '2026-08-15T11:05:00Z', type: 'case_mention', title: 'FIR 205/2026 filed', entityIds: ['p-vijay', 'acc-x'], evidenceId: 'ev-fir-205' },
  { id: 't-8', caseId: 'case-205', timestamp: '2026-08-17T10:00:00Z', type: 'transfer', title: 'Transfer Account B → Account X (88,000)', entityIds: ['acc-b', 'acc-x'], evidenceId: 'ev-txn-205' },
  { id: 't-9', caseId: 'case-205', timestamp: '2026-08-18T16:00:00Z', type: 'sighting', title: 'Vijay Menon visits Harbor Warehouse 7', entityIds: ['p-vijay', 'loc-harbor'], evidenceId: 'ev-fir-205' },
  { id: 't-10', caseId: 'case-205', timestamp: '2026-08-20T13:00:00Z', type: 'transfer', title: 'Transfer Account B → Account X (86,500)', entityIds: ['acc-b', 'acc-x'], evidenceId: 'ev-txn-205' },
]

// -------------------------------------------------------------------------------------
// CROSS-CASE LINKS
// -------------------------------------------------------------------------------------
export const crossCaseLinks: CrossCaseLink[] = [
  {
    id: 'cc-1',
    canonicalId: 'p-ravi',
    label: 'Ravi Kumar / R. Kumar',
    type: 'person',
    confidence: 92,
    caseIds: ['case-101', 'case-205'],
    reasons: ['Matching phone line 43210', 'High name similarity', 'Overlapping association with Meridian Traders'],
  },
  {
    id: 'cc-2',
    canonicalId: 'tel-1',
    label: '+91 98765 43210',
    type: 'phone',
    confidence: 96,
    caseIds: ['case-101', 'case-205'],
    reasons: ['Identical subscriber line present in CDR evidence of both cases'],
  },
  {
    id: 'cc-3',
    canonicalId: 'org-meridian',
    label: 'Meridian Traders',
    type: 'org',
    confidence: 79,
    caseIds: ['case-101', 'case-205'],
    reasons: ['Referenced in filings of both investigations'],
  },
]

// -------------------------------------------------------------------------------------
// AUDIT LOG (seed history)
// -------------------------------------------------------------------------------------
export const auditSeed: AuditEntry[] = [
  { id: 'a-1', timestamp: '2026-08-28T08:20:00Z', userId: 'u-dev', action: 'VIEW', caseId: 'case-205', resource: 'Case overview', result: 'success' },
  { id: 'a-2', timestamp: '2026-08-27T16:40:00Z', userId: 'u-mira', action: 'FINDING_ACKNOWLEDGE', caseId: 'case-101', resource: 'f-comms', result: 'success' },
  { id: 'a-3', timestamp: '2026-08-27T15:02:00Z', userId: 'u-lena', action: 'QUERY', caseId: 'case-101', resource: 'Copilot: why is Ravi Kumar important', result: 'success' },
  { id: 'a-4', timestamp: '2026-08-26T11:14:00Z', userId: 'u-arjun', action: 'VIEW', caseId: 'case-205', resource: 'Case overview', result: 'denied' },
  { id: 'a-5', timestamp: '2026-08-22T14:10:00Z', userId: 'u-lena', action: 'UPLOAD', caseId: 'case-205', resource: 'Transactions205.csv', result: 'success' },
  { id: 'a-6', timestamp: '2026-08-20T09:00:00Z', userId: 'u-mira', action: 'LOGIN', resource: 'Session', result: 'success' },
]
