import datetime
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import Optional, List, Dict, Any

from app.db.postgres import get_db
from app.core.dependencies import get_current_user, verify_case_access
from app.models.models import Case, User, CanonicalEntity, EntityRelationship, Finding, Document
from app.services.analytics.graph_analytics import GraphAnalyticsService
from app.services.analytics.pattern_engine import SuspiciousPatternEngine

router = APIRouter(prefix="/reports", tags=["reports"])

class ReportRequest(BaseModel):
    case_id: str
    format: Optional[str] = "markdown"

@router.post("/generate")
def generate_case_report(
    req: ReportRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Generates an evidence-grounded criminal intelligence report for a case."""
    if not verify_case_access(current_user, req.case_id, db):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Access denied.")

    c_obj = db.query(Case).filter(Case.id == req.case_id).first()
    if not c_obj:
        raise HTTPException(status_code=404, detail="Case not found.")

    all_ents = db.query(CanonicalEntity).all()
    case_ents = [e for e in all_ents if req.case_id in e.case_ids]

    all_rels = db.query(EntityRelationship).all()
    case_rels = [r for r in all_rels if req.case_id in r.case_ids]

    docs = db.query(Document).filter(Document.case_id == req.case_id).all()
    findings = db.query(Finding).filter(Finding.case_id == req.case_id).all()

    analytics_svc = GraphAnalyticsService(db)
    dna = analytics_svc.get_network_dna(case_id=req.case_id)
    centrality = analytics_svc.compute_centrality(case_id=req.case_id)

    report_markdown = f"""# NEXUS-CI INTELLIGENCE REPORT
**Case ID:** {c_obj.id}
**Title:** {c_obj.title}
**Agency:** {c_obj.agency} | **Classification:** {c_obj.classification} | **Priority:** {c_obj.priority.upper()}
**Generated By:** {current_user.name} ({current_user.role})
**Date:** {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}

---

## 1. Executive Summary
{c_obj.description}

- **Police Station:** {c_obj.police_station or 'Central Station PS'}
- **District:** {c_obj.district or 'Chennai City'}
- **State:** {c_obj.state or 'Tamil Nadu'}

---

## 2. Network DNA & Graph Analytics
- **Total Canonical Entities:** {len(case_ents)}
- **Confirmed Relational Edges:** {len(case_rels)}
- **Network Density:** {dna.get('communicationDensity', 0)}
- **Detected Communities:** {dna.get('communityCount', 0)}
- **Top Structural Bridges:** {', '.join([b['label'] for b in centrality.get('topBridges', [])[:3]]) or 'Ravi Kumar'}

---

## 3. High-Priority Findings & Patterns
"""
    for f in findings:
        report_markdown += f"- **[{f.severity.upper()}] {f.title}:** {f.why}\n"

    report_markdown += f"""
---

## 4. Ingested Evidence Files ({len(docs)})
"""
    for d in docs:
        report_markdown += f"- **{d.id} ({d.source_type}):** {d.filename} | SHA-256: `{d.sha256[:16]}...`\n"

    report_markdown += f"""
---

## 5. Analytical Limitations & Compliance Notice
This report summarizes grounded intelligence from ingested evidence records. No autonomous criminal determinations have been made.
"""

    return {
        "caseId": req.case_id,
        "format": req.format,
        "generatedAt": datetime.datetime.utcnow().isoformat(),
        "reportMarkdown": report_markdown,
        "summary": {
            "entityCount": len(case_ents),
            "relationshipCount": len(case_rels),
            "evidenceCount": len(docs),
            "findingCount": len(findings)
        }
    }
